services:
  postgres:
    image: postgres:15-alpine
    container_name: sydykov_postgres
    environment:
      POSTGRES_USER: sydykov_user
      POSTGRES_PASSWORD: sydykov_password
      POSTGRES_DB: sydykov_bot
    ports:
      - '5433:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sydykov_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sydykov_user -d sydykov_bot']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sydykov_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - sydykov_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  sydykov_network:
    driver: bridge
